### ISSUE TITLE
Error when creating a PVC over a StorageClass on openebs

### ISSUE THREAD

**Issue by davidcodesido** [openebs/maya#756]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT

**What happened**: When creating a PVC over a StorageClass  I'm getting an unknown error in maya's logs and the PVC/PV is not being created. I'm leaned to think that it is related to the long names that kube-prometheus and prometheus-operator use for this (it is not configured like that from me) since other PVC/SCs that I've been creating worked without any issue.

**What you expected to happen**: The PVC works as the others.

**How to reproduce it (as minimally and precisely as possible)**: 

Storage class:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  creationTimestamp: 2018-10-23T16:35:13Z
  name: openebs-alertmanager
  resourceVersion: "2181396"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/openebs-alertmanager
  uid: 9da3e8d7-d6e1-11e8-869c-067c2e000c39
parameters:
  openebs.io/capacity: 10G
  openebs.io/jiva-replica-count: "3"
  openebs.io/storage-pool: default
  openebs.io/volume-monitor: "true"
provisioner: openebs.io/provisioner-iscsi
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

PVC:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"856c5804-d6ae-11e8-9be1-c60f2f265b0f","leaseDurationSeconds":15,"acquireTime":"2018-10-23T17:12:05Z","renewTime":"2018-10-23T17:34:56Z","leaderTransitions":0}'
    volume.beta.kubernetes.io/storage-provisioner: openebs.io/provisioner-iscsi
  creationTimestamp: 2018-10-23T17:12:05Z
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    alertmanager: kube-prometheus
    app: alertmanager
  name: alertmanager-kube-prometheus-db-alertmanager-kube-prometheus-0
  namespace: monitoring
  resourceVersion: "2192319"
  selfLink: /api/v1/namespaces/monitoring/persistentvolumeclaims/alertmanager-kube-prometheus-db-alertmanager-kube-prometheus-0
  uid: c40bab23-d6e6-11e8-869c-067c2e000c39
spec:
  accessModes:
  - ReadWriteOnce
  dataSource: null
  resources:
    requests:
      storage: 10Gi
  storageClassName: openebs-alertmanager
status:
  phase: Pending
```

**Anything else we need to know?**: These are the logs I see from maya:

```
2018/10/23 17:29:21.193654 [DEBUG] http: Request /latest/volumes/monitoring-alertmanager-kube-prometheus-db-alertmanager-kube-prometheus-0-786827526 (GET)
I1023 17:29:21.193688       8 volume_endpoint_v1alpha1.go:31] cas template based volume request was received: method 'GET'
I1023 17:29:21.193702       8 volume_endpoint_v1alpha1.go:117] cas template based volume read request was received
E1023 17:29:21.214131       8 runner.go:211] failed to execute runtask: name 'jiva-volume-isvalidversion-default-0.7.0': meta yaml 'id: is070jivavolume
runNamespace: {{.Volume.runNamespace}}
apiVersion: v1
kind: Service
action: list
options: |-
  labelSelector: vsm={{ .Volume.owner }}
': task yaml '': template values in yaml 'Config: {}
JsonResult: --redacted--
ListItems: {}
TaskResult:
  is070jivavolume:
    verifyErr: null
Volume:
  owner: monitoring-alertmanager-kube-prometheus-db-alertmanager-kube-prometheus-0-786827526
  runNamespace: monitoring
': template values 'map[JsonResult:--redacted-- Config:map[] TaskResult:map[is070jivavolume:map[verifyErr:<nil>]] ListItems:map[] Volume:map[owner:monitoring-alertmanager-kube-prometheus-db-alertmanager-kube-prometheus-0-786827526 runNamespace:monitoring]]'
W1023 17:29:21.214172       8 runner.go:276] the server rejected our request for an unknown reason (get services): failed to execute runtasks
W1023 17:29:21.214180       8 runner.go:162] nothing to rollback: no rollback tasks were found
E1023 17:29:21.214186       8 volume_endpoint_v1alpha1.go:155] failed to read cas template based volume: error 'the server rejected our request for an unknown reason (get services)'
2018/10/23 17:29:21.214194 [ERR] http: Request GET /latest/volumes/monitoring-alertmanager-kube-prometheus-db-alertmanager-kube-prometheus-0-786827526, error: the server rejected our request for an unknown reason (get services)
2018/10/23 17:29:21.214211 [DEBUG] http: Request /latest/volumes/monitoring-alertmanager-kube-prometheus-db-alertmanager-kube-prometheus-0-786827526 (20.560466ms)
```

**Environment**:
- Maya version (use `maya version`): -
- M-apiserver version (use `m-apiserver version`): maya-apiserver version
Version: 0.7.0-unreleased
Git commit: 13a810528234e40c8121705e2957dc8d5dfe9519
GO Version: go1.10.3
GO ARCH: amd64
GO OS: linux
Provider:  KUBERNETES
- OS (e.g. from /etc/os-release): Debian 9
- Kernel (e.g. `uname -a`): Linux 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux
- Install tools: helm 
- Others:

**Comment by princerachit** [comment]
@davidcodesido this bug has been fixed in 0.7.1 release. [Here is the PR which fixes this issue.](https://github.com/openebs/external-storage/pull/74)

**Comment by davidcodesido** [comment]
Thanks.

**Comment by gabrielcalderon** [comment]
This error still shows up in the latest version of Openebs with Rancher 2.2.2, when using the built-in grafana/prometheus metrics.
